# Generated by Django 5.2.8 on 2025-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weatherquery',
            name='weather_que_timesta_78d43d_idx',
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['timestamp', 'served_from_cache'], name='weather_que_timesta_5358cd_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['ip_address', 'timestamp'], name='weather_que_ip_addr_71b291_idx'),
        ),
    ]
